### ISSUE TITLE
Qt on Linux

### ISSUE THREAD

**Issue by JustinPedersen96** [mgear-dev/mgear#15]
When opening ui elements on a Linux install, the QT imports fail. 

OS: CentOs7
mGear : v4.0.0
Maya: 2022
Python: 3

```
[...]/mGear/v4.0.0/scripts/mgear/__init__.py
# Error: No module named 'Qt'
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "/usr/autodesk/maya2022/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
#     return original_import(name, *args, **kwargs)
#   File "[...]/mGear/v4.0.0/scripts/mgear/shifter/guide_manager_gui.py", line 1, in <module>
#     from mgear.shifter import guide_manager_component, guide_template_explorer
#   File "/usr/autodesk/maya2022/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
#     return original_import(name, *args, **kwargs)
#   File "[...]/mGear/v4.0.0/scripts/mgear/shifter/guide_template_explorer.py", line 10, in <module>
#     from mgear.vendor.qjsonmodel import QJsonModel
#   File "/usr/autodesk/maya2022/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
#     return original_import(name, *args, **kwargs)
#   File "[...]/mGear/v4.0.0/scripts/mgear/vendor/qjsonmodel.py", line 42, in <module>
#     from Qt import QtWidgets, QtCore, __binding__
#   File "/usr/autodesk/maya2022/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
#     return original_import(name, *args, **kwargs)
# ModuleNotFoundError: No module named 'Qt' # 
```

**Comment by miquelcampos** [comment]
Thanks for the feedback @JustinPedersen96   
I have to get a Linux machine to test properly :P

**Comment by JustinPedersen96** [comment]
@miquelcampos Happy to do any testing for you on my side if needed! We are really eager to get mGear4 into our maya 2022 area of the pipeline!

**Comment by miquelcampos** [comment]
@JustinPedersen96 is just the relative import in Python3.
