### ISSUE TITLE
synoptic issue

### ISSUE THREAD

**Issue by niteshms04** [mgear-dev/mgear#234]
Hi miguel.

Ive been trying to make my synoptic work but havent been able to.this is the error which i get. please look into it.

```
Loading synoptic tab of biped
# Traceback (most recent call last):
#   File "/home/au02/maya/2017/modules/scripts/mgear/maya/synoptic/__init__.py", line 221, in updateTabs
#     synoptic_tab = getattr(module, "SynopticTab")()
#   File "/home/au02/maya/2017/modules/scripts/mgear/maya/synoptic/tabs/biped/__init__.py", line 30, in __init__
#     super(SynopticTab, self).__init__(self, parent)
#   File "/home/au02/maya/2017/modules/scripts/mgear/maya/synoptic/tabs/__init__.py", line 46, in __init__
#     klass.connectMaya()
#   File "/home/au02/maya/2017/modules/scripts/mgear/maya/synoptic/tabs/__init__.py", line 90, in connectMaya
#     gui = OpenMayaUI.MQtUtil.fullName(ptr)
# TypeError: Expected argument of type long
# Error: Synoptic tab: %s Loading fail biped
Expected argument of type long # 
Loading synoptic tab of biped
# Traceback (most recent call last):
#   File "/home/au02/maya/2017/modules/scripts/mgear/maya/synoptic/__init__.py", line 221, in updateTabs
#     synoptic_tab = getattr(module, "SynopticTab")()
#   File "/home/au02/maya/2017/modules/scripts/mgear/maya/synoptic/tabs/biped/__init__.py", line 30, in __init__
#     super(SynopticTab, self).__init__(self, parent)
#   File "/home/au02/maya/2017/modules/scripts/mgear/maya/synoptic/tabs/__init__.py", line 46, in __init__
#     klass.connectMaya()
#   File "/home/au02/maya/2017/modules/scripts/mgear/maya/synoptic/tabs/__init__.py", line 90, in connectMaya
#     gui = OpenMayaUI.MQtUtil.fullName(ptr)
# TypeError: Expected argument of type long
# Error: Synoptic tab: %s Loading fail biped
Expected argument of type long # 
```
Also i've been trying to import blendShapes using custom steps but havn't been able to. Could you make a quick video of how to do it. ThankYou

**Comment by miquelcampos** [comment]
Hi @niteshms04  I think this belongs to the support category in the forum. 
If you did a custom tab for you synoptic, I need to see source. But can't promise anything. I hope you understand.

**Comment by niteshms04** [comment]
i havent made any custom tab fot the synoptic. Ive been trying to use the defaut synoptic in the script folder.

**Comment by miquelcampos** [comment]
@niteshms04 Oh I see. I was thinking you did a custom configuration because you said:
>  Ive been trying to make my synoptic work

Anyway, Looks like can't find the synoptic tab. Are you working with OSX?

**Comment by niteshms04** [comment]
linux CentOS.
