### ISSUE TITLE
Shifter: Squash_01 add scale multipliers

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear#339]
- Add multipliers for squash and streatch in XYZ 
- Add SDK input transform

**Comment by joji2468ng** [comment]
Hi @miquelcampos,

It seems like we can't open the guide setting UI after merging.

```# Traceback (most recent call last):
#   File "C:\Users\georg\OneDrive\Documents\maya\GitHub\mgear4\release\scripts\mgear\shifter\guide_manager.py", line 104, in inspect_settings
#     wind = pyqt.showDialog(guide.componentSettings, dockable=True)
#   File "C:\Users\georg\OneDrive\Documents\maya\GitHub\mgear4\release\scripts\mgear\core\pyqt.py", line 167, in showDialog
#     windw = dialog()
#   File "C:/Users/georg/OneDrive/Documents/maya/GitHub/mgear4/release/scripts/mgear/shifter_classic_components\squash_01\guide.py", line 100, in __init__
#     self.populate_componentControls()
#   File "C:/Users/georg/OneDrive/Documents/maya/GitHub/mgear4/release/scripts/mgear/shifter_classic_components\squash_01\guide.py", line 129, in populate_componentControls
#     self.settingsTab.squashX_slider.setValue(int(self.root.attr("squashX").get() * 100))
# AttributeError: 'settingsTab' object has no attribute 'squashX_slider'```

**Comment by miquelcampos** [comment]
@joji2468ng  the error is because the guide has not been updated. The Squash_01 has new attrs. Use update guide command form the menu or from the right click context menu.
If the guide is serialized in .sgt format will automatically update at import time ;)
